config/routes.rb
Rails.application.routes.draw do
  root "games#home"

  resources :games, only: [:show, :create, :update, :destroy, :index]
  get "/games/:id/over", to: "games#over", as: "over_game"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/games.rb
class Games < ApplicationRecord
  before_create :generate_id
  serialize :deck, class: CardGame::Deck, coder: YAML
  serialize :discard, class: CardGame::Deck, coder: YAML
  serialize :vault, class: CardGame::Deck, coder: YAML
  serialize :assets, class: CardGame::Row, coder: YAML
  serialize :public_sales, class: CardGame::Row, coder: YAML
  serialize :private_sales, class: CardGame::Row, coder: YAML
  serialize :game_state, class: Symbol, coder: YAML

  def setup
    self.deck = CardGame::Deck.new(:standard)
    self.deck.shuffle

    self.discard = CardGame::Deck.new(:empty)
    self.vault = CardGame::Deck.new(:empty)

    self.assets = CardGame::Row.new(5)
    self.public_sales = CardGame::Row.new(5)
    self.private_sales = CardGame::Row.new(5)

    self.game_state = :in_progress

    refill_public_sales
    refill_assets
  end

  def valid_transaction?(bought_index, sold_indeces)
    if bought_index == nil || sold_indeces == nil
      return false
    end

    sold = sold_indeces.map { |i| self.assets[i] }
    bought = market_card(bought_index)

    return valid_purchase?(bought, sold) || valid_swap?(bought, sold)
  end

  def perform_transaction(bought_index, sold_indeces)
    sold_indeces.each do |i|
      self.discard.place(self.assets.take_at(i))
    end

    if bought_index <= 4
      card = self.public_sales.take_at(bought_index)
    else
      card = self.private_sales.take_at(bought_index - 5)
    end
    
    if card.face?
      self.vault.place(card)
    else
      self.assets.replenish(card)
    end

    cleanup
    update_gamestate
  end

  private

  def cleanup
    self.private_sales.compact
    refill_public_sales
    refill_assets
  end

  def update_gamestate
    if !any_valid_transactions?
      self.game_state = :lost_frozen
    elsif self.private_sales.overflow?
      self.game_state = :lost_overflow
    elsif self.vault.size == 12
      self.game_state = :won
    else
      self.game_state = :in_progress
    end
  end

  def any_valid_transactions?
    self.assets.each do |card|
      sold = Array.new
      sold.push(card)

      self.private_sales.each do |bought|
        if valid_swap?(bought, sold)
          return true
        end
      end
      self.public_sales.each do |bought|
        if valid_swap?(bought, sold)
          return true
        end
      end
    end

    assets = Hash.new
    assets[:clubs] = Array.new
    assets[:diamonds] = Array.new
    assets[:hearts] = Array.new
    assets[:spades] = Array.new

    self.assets.each do |card|
      if card == nil
        return
      end
      
      assets[card.suit].push(card)
    end
    
    assets.each do |suit, sold|
      self.private_sales.each do |bought|
        if valid_purchase?(bought, sold)
          return true
        end
      end
      self.public_sales.each do |bought|
        if valid_purchase?(bought, sold)
          return true
        end
      end
    end

    return false
  end

  def valid_purchase?(bought, sold)
    if bought == nil || sold.empty? || sold.any?(nil)
      return false
    end

    suit = sold.first.suit
    if !sold.all? { |card| card.suit == suit } || bought.suit != suit
      return false
    end

    sum = sold.sum { |card| sold_value(card) }
    if sum < bought.value
      return false
    end
    
    return true
  end

  def valid_swap?(bought, sold)
    if bought == nil  || sold.size != 1 || sold.any?(nil)
      return false
    end

    return bought.value == sold.first.value
  end

  def refill_assets
    while self.assets.empty_slots? && !self.deck.empty?
      card = deck.draw
      if !card.face?
        self.assets.replenish(card)
      else 
        self.private_sales.replenish(card)
      end
    end
  end

  def refill_public_sales
    while self.public_sales.empty_slots? && !self.deck.empty?
      card = deck.draw

      self.public_sales.replenish(card)
    end
  end

  def market_card(i)
    if i <= 4
      card = self.public_sales[i]
    else
      card = self.private_sales[i - 5]
    end
    return card
  end

  def sold_value(card)
    if card.value == 1
      return 11
    end

    return card.value
  end

  def generate_id
    loop do
      self.id = SecureRandom.alphanumeric(6).downcase
      break if not Games.where(id: self.id).exists?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def home
  end

  def show
    @game = Games.find(params[:id])

    if params.key?(:message)
      @message = params[:message]
    else
      @message = "Curator"
    end
  end

  def index
    if Games.exists?(params[:id])
      redirect_to game_path(params[:id])
    else
      redirect_to root_path
    end
  end

  def create
    @game = Games.new
    @game.setup
    @game.save
    
    redirect_to @game
  end

  def update
    @game = Games.find(params[:id])
    convert_params
  
    if @game.valid_transaction? params[:bought], params[:sold]
      @game.perform_transaction params[:bought], params[:sold]
      @game.save
    else
      message = "Invalid Transaction"
    end

    if @game.game_state == :in_progress 
      redirect_to game_path(@game, message: message)
    else
      redirect_to over_game_path(@game)
    end
  end

  def destroy
    @game = Games.find(params[:id])
    @game.destroy

    redirect_to root_path, status: :see_other
  end

  def over
    @game = Games.find(params[:id])

    if @game.game_state == :in_progress
      redirect_to @game
    else
      case @game.game_state
      when :won
        @message = "Victory"
      when :lost_frozen
        @message = "Defeat: No Valid Transactions"
      when :lost_overflow
        @message = "Defeat: Private Sales Overflow"
      end

      @game.destroy
    end
  end

  private
  
  def convert_params
    if params.key?(:bought)
      params[:bought] = params[:bought].to_i
    end
    if params.key?(:sold)
      params[:sold] = params[:sold].map { |index| index.to_i }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
  def card_svg(card)
    if card.nil?
      return "blank.svg"
    end
    
    svg = String.new

    case card.value
    when 2..10
      svg += card.value.to_s
    when 1
      svg += "ace"
    when 11
      svg += "jack"
    when 12
      svg += "queen"
    when 13
      svg += "king"
    end

    svg += "_of_"

    case card.suit
    when :clubs
      svg += "clubs"
    when :diamonds
      svg += "diamonds"
    when :hearts
      svg += "hearts"
    when :spades
      svg += "spades"
    end

    svg += ".svg"
    return svg
  end

  def card_png(card)
    if card.nil?
      return "blank_white.png"
    end
    
    png = String.new
    case card.value
    when 2..10
      png += card.value.to_s
    when 1
      png += "ace"
    when 11
      png += "jack"
    when 12
      png += "queen"
    when 13
      png += "king"
    end
    
    png += "_"

    case card.suit
    when :clubs
      png += "clubs"
    when :diamonds
      png += "diamonds"
    when :hearts
      png += "hearts"
    when :spades
      png += "spades"
    end

    png += "_white.png"
    return png
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def card_svg(card)
    if card.nil?
      return "blank.svg"
    end
    
    svg = String.new

    case card.value
    when 2..10
      svg += card.value.to_s
    when 1
      svg += "ace"
    when 11
      svg += "jack"
    when 12
      svg += "queen"
    when 13
      svg += "king"
    end

    svg += "_of_"

    case card.suit
    when :clubs
      svg += "clubs"
    when :diamonds
      svg += "diamonds"
    when :hearts
      svg += "hearts"
    when :spades
      svg += "spades"
    end

    svg += ".svg"
    return svg
  end

  def card_png(card)
    if card.nil?
      return "blank_white.png"
    end
    
    png = String.new
    case card.value
    when 2..10
      png += card.value.to_s
    when 1
      png += "ace"
    when 11
      png += "jack"
    when 12
      png += "queen"
    when 13
      png += "king"
    end
    
    png += "_"

    case card.suit
    when :clubs
      png += "clubs"
    when :diamonds
      png += "diamonds"
    when :hearts
      png += "hearts"
    when :spades
      png += "spades"
    end

    png += "_white.png"
    return png
  end
end

app/views/games/_game_board.html.erb
<div class="container-xl text-center">
  <p class="text-secondary fs-3 text-decoration-underline mb-1">Private Sales</p>
  <div class="row mb-4">
    <% for i in 0..4 %>
      <div class="col">
        <%= image_tag card_png(@game.private_sales[i]), class: "border-3 border-secondary p-1", width: 190, style: "image-rendering: pixelated", name: "buy-button",  data: { index: @game.private_sales[i] == nil ? -1 : i + 5 } %>
      </div>
    <% end %>
  </div>
  <p class="text-secondary fs-3 text-decoration-underline mb-1">Public Sales</p>
  <div class="row mb-4">
    <% for i in 0..4 %>
      <div class="col">
        <%= image_tag card_png(@game.public_sales[i]), class: "border-3 border-secondary p-1", width: 190, style: "image-rendering: pixelated", name: "buy-button",  data: { index: @game.public_sales[i] == nil ? -1 : i } %>
      </div>
    <% end %>
  </div>
  <div class ="row mb-1">
    <div class="col">
      <span class="badge text-primary text-bg-secondary rounded-pill fs-4"><%= "Deck: #{@game.deck.size} cards" %></span>
    </div>
    <div class="col">
      <span class="badge text-primary text-bg-secondary rounded-pill fs-4"><%= "Discard: #{@game.discard.size} cards" %></span>
    </div>
    <div class="col">
      <span class="badge text-primary text-bg-secondary rounded-pill fs-4"><%= "Vault: #{@game.vault.size} portraits" %></span>
    </div>
  </div>
  <p class="text-secondary fs-3 text-decoration-underline mb-1">Assets</p>
  <div class="row mb-4">
    <% for i in 0..4 %>
      <div class="col">
        <%= image_tag card_png(@game.assets[i]), class: "border-3 border-secondary p-1", width: 230, style: "image-rendering: pixelated", name: "sell-button",  data: { index: @game.assets[i] == nil ? -1 : i } %>
      </div>
    <% end %>
  </div>
  <div class="row mb-4">
    <%= button_to "Confirm", game_path(@game), method: :patch, id: "confirm-button", class: "btn btn-secondary btn-lg text-primary w-75", disabled: true, form: { id: "confirm-form" } %>
  </div>
</div>

app/views/games/_game_board_over.html.erb
<div class="container-xl text-center">
  <div class ="row mb-1">
    <span class="badge text-primary text-bg-secondary rounded-pill fs-4"><%= "Vault: #{@game.vault.size} portraits" %></span>
  </div>
  <p class="text-secondary fs-3 text-decoration-underline mb-1">Private Sales</p>
  <div class="row mb-4">
    <% for i in 0..4 %>
      <div class="col">
        <%= image_tag card_png(@game.private_sales[i]), class: "border-3 border-secondary p-1", width: 190, style: "image-rendering: pixelated" %>
      </div>
    <% end %>
  </div>
  <p class="text-secondary fs-3 text-decoration-underline mb-1">Public Sales</p>
  <div class="row mb-4">
    <% for i in 0..4 %>
      <div class="col">
        <%= image_tag card_png(@game.public_sales[i]), class: "border-3 border-secondary p-1", width: 190, style: "image-rendering: pixelated" %>
      </div>
    <% end %>
  </div>
  <p class="text-secondary fs-3 text-decoration-underline mb-1">Assets</p>
  <div class="row mb-4">
    <% for i in 0..4 %>
      <div class="col">
        <%= image_tag card_png(@game.assets[i]), class: "border-3 border-secondary p-1", width: 190, style: "image-rendering: pixelated" %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/_game_header.html.erb
<div class="container-fluid">
  <div class="row m-3">
    <div class="col text-start">
      <span class="badge text-primary text-bg-secondary rounded-pill fs-4"><%= "Game ID: #{@game.id}" %></span>
    </div>
    <div class="col text-center">
      <span class="text-secondary fs-2 fw-bold"><%= @message %></span>
    </div>
    <div class="col text-end">
      <%= button_to "Forfeit", game_path(@game), method: :delete, class: "btn btn-secondary btn-lg text-primary" %>
    </div>
  </div>
</div>

app/views/games/_game_header_over.html.erb
<div class="container-fluid">
  <div class="row m-3">
    <div class="col text-start">
      <span class="badge text-primary text-bg-secondary rounded-pill fs-4"><%= "Game ID: #{@game.id}" %></span>
    </div>
    <div class="col text-center">
      <span class="text-secondary fs-2 fw-bold"><%= @message %></span>
    </div>
    <div class="col text-end">
      <%= button_to "New Game", games_path, method: :post, class: "btn btn-secondary btn-lg text-primary" %>
    </div>
  </div>
</div>

app/views/games/home.html.erb
<div class="container-xl d-flex flex-column align-items-center">
  <%= image_tag "logo.png", width: "100%", class: "my-4", style: "image-rendering: pixelated" %>
  <%= button_to "New Game", games_path, method: :post, class: "btn btn-secondary btn-lg text-primary mb-4", style: "width: 600px" %>
  <span class="text-secondary fs-4 fst-italic mb-4">or</span>
  <%= form_with url: "/games", method: :get do |form| %>
    <div class="input-group" style="width: 600px">
      <span class="input-group-text text-primary text-bg-secondary">Game ID</span>
      <%= form.text_field :id, class: "form-control bg-light" %>
      <%= form.submit "Continue Game", class: "btn btn-secondary btn-lg text-primary btn-outline-secondary" %>
  <% end %>
</div>

app/views/games/over.html.erb
<%= render "game_header_over" %>
<%= render "game_board_over" %>

app/views/games/show.html.erb
<%= render "game_header" %>
<%= render "game_board" %>
<%= javascript_include_tag "game_show.js", "data-turbo-track": "reload", type: "module" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Curator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="bg-primary">
    <%= yield %>
  </body>
</html>